In [1]:
import numpy as np

# Створимо матрицю A
A = np.array([[1,2],
              [4, -1]])

# Створимо матрицю B
B = np.array([[2,-3],
              [4, 1]])

# Обчислимо матрицю C
C = np.dot(A, B) - np.dot(B, A)

print("Матриця C:")
print(C)

Матриця C:
[[ 20  -8]
 [ -4 -20]]


In [2]:
import numpy as np

# Створимо матрицю A
A = np.array([[-1,2],
              [0, 1]])

# Обчислимо матрицю C
C = pow(A,2)


print(C)


[[1 4]
 [0 1]]


In [3]:
import numpy as np

# Створимо матрицю A
A = np.array([[3,5],
              [6, -1]])

# Створимо матрицю B
B = np.array([[2,1],
              [-3, 2]])

# Обчислимо матрицю C
C = A * B

print("Матриця C:")
print(C)

Матриця C:
[[  6   5]
 [-18  -2]]


In [5]:
import numpy as np

# Для матриці 4x4
B = np.array([[1, 2, 3,4],
              [3, -1, 2,5],
              [1, 2, 3,4],
              [1,3,4,5]
              ])

det_4x4 = np.linalg.det(B)


print("Визначник матриці 4x4:", det_4x4)

Визначник матриці 4x4: 0.0


In [6]:
import numpy as np

A = np.array([[1, -2, 1],
              [2, -1, 1],
              [3, 2, 2]])

B = np.array([4, 3, 2])
detA = np.linalg.det(A)

A_x = A.copy()
A_x[:, 0] = B
detA_x = np.linalg.det(A_x)

A_y = A.copy()
A_y[:, 1] = B
detA_y = np.linalg.det(A_y)

A_z = A.copy()
A_z[:, 2] = B
detA_z = np.linalg.det(A_z)

x = detA_x / detA
y = detA_y / detA
z = detA_z / detA

print("Решение:")
print("x =", x)
print("y =", y)
print("z =", z)



Решение:
x = 0.0
y = -1.0
z = 2.0


In [ ]:
import numpy as np

# Для матриці 3x3
B = np.array([[2, 3, 4],
              [1, 0, 6],
              [7, 8, 9]])

det_3x3 = np.linalg.det(B)


print("Визначник матриці 3x3:", det_3x3)


In [7]:
import numpy as np
N = 5
M = 6 

A = np.random.randint(1, 11, size=(N, M))

total_sum = np.sum(A)

column_sums = np.sum(A, axis=0)

column_fractions = column_sums / total_sum

print("Матриця A:")
print(A)

print("\nСума всіх елементів матриці:", total_sum)

print("\nСуми елементів кожного стовпця:")
for i, col_sum in enumerate(column_sums):
    print(f"Сума стовпця {i + 1}: {col_sum}")

print("\nДолі сум елементів кожного стовпця відносно загальної суми:")
for i, fraction in enumerate(column_fractions):
    print(f"Доля стовпця {i + 1}: {fraction:.2%}")


Матриця A:
[[ 6  8  3  2 10  5]
 [ 6  9  2  5  3  7]
 [ 7  2  1  5  2  9]
 [ 2  5  2  7 10 10]
 [ 1  6 10  8  9  7]]

Сума всіх елементів матриці: 169

Суми елементів кожного стовпця:
Сума стовпця 1: 22
Сума стовпця 2: 30
Сума стовпця 3: 18
Сума стовпця 4: 27
Сума стовпця 5: 34
Сума стовпця 6: 38

Долі сум елементів кожного стовпця відносно загальної суми:
Доля стовпця 1: 13.02%
Доля стовпця 2: 17.75%
Доля стовпця 3: 10.65%
Доля стовпця 4: 15.98%
Доля стовпця 5: 20.12%
Доля стовпця 6: 22.49%


# Introduction to the JupyterLab and Jupyter Notebooks

This is a short introduction to two of the flagship tools created by [the Jupyter Community](https://jupyter.org).

> **⚠️Experimental!⚠️**: This is an experimental interface provided by the [JupyterLite project](https://jupyterlite.readthedocs.io/en/latest/). It embeds an entire JupyterLab interface, with many popular packages for scientific computing, in your browser. There may be minor differences in behavior between JupyterLite and the JupyterLab you install locally. You may also encounter some bugs or unexpected behavior. To report any issues, or to get involved with the JupyterLite project, see [the JupyterLite repository](https://github.com/jupyterlite/jupyterlite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

## JupyterLab 🧪

**JupyterLab** is a next-generation web-based user interface for Project Jupyter. It enables you to work with documents and activities such as Jupyter notebooks, text editors, terminals, and custom components in a flexible, integrated, and extensible manner. It is the interface that you're looking at right now.

**For an overview of the JupyterLab interface**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Welcome Tour` and following the prompts.

> **See Also**: For a more in-depth tour of JupyterLab with a full environment that runs in the cloud, see [the JupyterLab introduction on Binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/HEAD?urlpath=lab/tree/demo).

## Jupyter Notebooks 📓

**Jupyter Notebooks** are a community standard for communicating and performing interactive computing. They are a document that blends computations, outputs, explanatory text, mathematics, images, and rich media representations of objects.

JupyterLab is one interface used to create and interact with Jupyter Notebooks.

**For an overview of Jupyter Notebooks**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Notebook Tour` and following the prompts.

> **See Also**: For a more in-depth tour of Jupyter Notebooks and the Classic Jupyter Notebook interface, see [the Jupyter Notebook IPython tutorial on Binder](https://mybinder.org/v2/gh/ipython/ipython-in-depth/HEAD?urlpath=tree/binder/Index.ipynb).

## An example: visualizing data in the notebook ✨

Below is an example of a code cell. We'll visualize some simple data using two popular packages in Python. We'll use [NumPy](https://numpy.org/) to create some random data, and [Matplotlib](https://matplotlib.org) to visualize it.

Note how the code and the results of running the code are bundled together.

In [8]:
import numpy as np

N = 6
M = 7  

A = np.random.randint(1, 11, size=(N, M))

total_sum = np.sum(A)

row_sums = np.sum(A, axis=1)

row_fractions = row_sums / total_sum

print("Матриця A:")
print(A)

print("\nСума всіх елементів матриці:", total_sum)

print("\nСуми елементів кожного рядка:")
for i, row_sum in enumerate(row_sums):
    print(f"Сума рядка {i + 1}: {row_sum}")

print("\nДолі сум елементів кожного рядка відносно загальної суми:")
for i, fraction in enumerate(row_fractions):
    print(f"Доля рядка {i + 1}: {fraction:.2%}")


Матриця A:
[[ 3 10  7  6  1  1  7]
 [ 4  3  4  3  2  1  3]
 [ 1  6  2  3  7  8  8]
 [ 6  4  9  4  9  2  6]
 [ 7 10  4  1 10  8  7]
 [ 2  8  3  8  1  4  5]]

Сума всіх елементів матриці: 208

Суми елементів кожного рядка:
Сума рядка 1: 35
Сума рядка 2: 20
Сума рядка 3: 35
Сума рядка 4: 40
Сума рядка 5: 47
Сума рядка 6: 31

Долі сум елементів кожного рядка відносно загальної суми:
Доля рядка 1: 16.83%
Доля рядка 2: 9.62%
Доля рядка 3: 16.83%
Доля рядка 4: 19.23%
Доля рядка 5: 22.60%
Доля рядка 6: 14.90%


In [9]:
import numpy as np
N = 4  
M = 5  

A = np.random.randint(-10, 11, size=(N, M))

negative_elements_in_columns = np.sum(A < 0, axis=0)
negative_elements_in_rows = np.sum(A < 0, axis=1)

print("Матриця A:")
print(A)

print("\nКількість негативних елементів в кожному стовпці:")
for i, count in enumerate(negative_elements_in_columns):
    print(f"Кількість негативних елементів у стовпці {i + 1}: {count}")

print("\nКількість негативних елементів в кожному рядку:")
for i, count in enumerate(negative_elements_in_rows):
    print(f"Кількість негативних елементів у рядку {i + 1}: {count}")


Матриця A:
[[  4   5 -10  -1  -5]
 [  7  -8  -6   6   4]
 [ -1   8  -4  -9  -8]
 [ -1  10   5  -4  10]]

Кількість негативних елементів в кожному стовпці:
Кількість негативних елементів у стовпці 1: 2
Кількість негативних елементів у стовпці 2: 1
Кількість негативних елементів у стовпці 3: 3
Кількість негативних елементів у стовпці 4: 3
Кількість негативних елементів у стовпці 5: 2

Кількість негативних елементів в кожному рядку:
Кількість негативних елементів у рядку 1: 3
Кількість негативних елементів у рядку 2: 2
Кількість негативних елементів у рядку 3: 4
Кількість негативних елементів у рядку 4: 2


## Next steps 🏃

This is just a short introduction to JupyterLab and Jupyter Notebooks. See below for some more ways to interact with tools in the Jupyter ecosystem, and its community.

### Other notebooks in this demo

Here are some other notebooks in this demo. Each of the items below corresponds to a file or folder in the **file browser to the left**.

- [**`Lorenz.ipynb`**](Lorenz.ipynb) uses Python to demonstrate interactive visualizations and computations around the [Lorenz system](https://en.wikipedia.org/wiki/Lorenz_system). It shows off basic Python functionality, including more visualizations, data structures, and scientific computing libraries.
- [**`sqlite.ipynb`**](sqlite.ipynb) demonstrates how an in-browser sqlite kernel to run your own SQL commands from the notebook. It uses the [jupyterlite/xeus-sqlite-kernel](https://github.com/jupyterlite/xeus-sqlite-kernel).

### Other sources of information in Jupyter

- **More on using JupyterLab**: See [the JupyterLab documentation](https://jupyterlab.readthedocs.io/en/stable/) for more thorough information about how to install and use JupyterLab.
- **More interactive demos**: See [try.jupyter.org](https://try.jupyter.org) for more interactive demos with the Jupyter ecosystem.
- **Learn more about Jupyter**: See [the Jupyter community documentation](https://docs.jupyter.org) to learn more about the project, its community and tools, and how to get involved.
- **Join our discussions**: The [Jupyter Community Forum](https://discourse.jupyter.org) is a place where many in the Jupyter community ask questions, help one another, and discuss issues around interactive computing and our ecosystem.